### ISSUE TITLE
Error: "File to import not found or unreadable:"

### ISSUE THREAD

**Issue by ghost** [chrisjimallen/bootstrap-4-gulp-browsersync#1]
I followed your steps but everytime i try to run gulp sass or serve i get the Error: "File to import not found or unreadable:" from app.scss file.

Any idea?

**Comment by chrisjimallen** [comment]
Looks like the bootstrap version is out of date, I will look into this over the weekend.

**Comment by ghost** [comment]
@chrisjimallen Yea i updated app.scss from bootstrap site and all went fine. :)

**Comment by chrisjimallen** [comment]
Feel free to submit a PR @squizyt i haven't had time to sort this yet. ;)

**Comment by ghost** [comment]
I don't have permission?

**Comment by chrisjimallen** [comment]
You'd need to fork the repo first. For now I've fixed the issue, but feel free to fork and submit a PR for any improvements. Its very early days.
